[package]
name = "signer-eigen"
version = "0.1.0"
edition = "2021"

[dependencies]
eigen-crypto-bls = { git = "https://github.com/dymchenkko/eigensdk-rs", rev = "dcba03cedc9af91fb982538c31ac9463134ef5e9" }
hex = "0.4"
ark-serialize = "0.5.0"
